import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Joseph Omotade Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <span className='text-6xl justify-center font-bold font-Clash items-center flex'>hello world</span>
        <span className='text-3xl justify-center font-bold font-panchanglight items-center flex'>hello world</span>
      
    </div>
  )
}

export default Home
